all: compile run

compile:
	@echo ''
	@echo "Compiling java files in order of dependency"
	@nxjpcc *.java

run:
	@echo ''
	@echo "Running the Program"
	@nxjpc Qlearning

clean:
	@echo "Removing binary files"
	@rm *.class
